server:
  port: 0
spring:
  cloud:
    config:
      enabled: false
  application:
    name: DEPARTMENT

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
